version: '3.5'
services:
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres/dispensary -schemas=canna -user=user -password=changeme -baselineOnMigrate=true -connectRetries=60 migrate
    volumes:
      - ./src/main/resources/flyway/migrations:/flyway/sql
    depends_on:
      - postgres
    networks:
      - canna-network

  postgres:
    image: postgres:11
    container_name: postgres_canna
    environment:
      POSTGRES_DB: dispensary
      POSTGRES_USER: user
      POSTGRES_PASSWORD: changeme
      PGDATA: /data/postgres
    volumes:
      - canna-volume:/data/postgres
    ports:
      - 5432:5432
    networks:
      - canna-network
    restart: unless-stopped

networks:
  canna-network:
    driver: bridge

volumes:
  canna-volume: